---
title: 'Tidy Tuesday #3'
author: "Kaiyang Yao"
output: 
  html_document:
    df_print: paged
    code_download: true
    theme: cerulean
---

```{r setup, include=FALSE}
# You may want to comment this out at first so you see important messages and warnings
knitr::opts_chunk$set(echo = TRUE, error=TRUE, message=FALSE, warning=FALSE)
```

```{r libraries}
library(tidyverse)     # for graphing and data cleaning
library(lubridate)     # for date manipulation
library(ggthemes)      # for even more plotting themes
theme_set(theme_minimal())       # My favorite ggplot() theme :)
```


```{r}
# Read in the data for the week
firsts <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-09/firsts.csv')
science <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-09/science.csv')
```

This week I want to explore the "first" accomplishments by African-American in different categories over years. The graph will also color coded by gender.

```{r}
firsts %>% 
  ggplot(aes(x = year, y = category, color = gender)) +
  geom_point() + 
  theme(plot.title = element_text(hjust = 1),
        legend.position = "top",
        legend.title = element_blank()) +
  labs(title = "African-American's accomplishments in different categories over years",
       x = "", y = "")
```
